INSERT INTO COLLABORATORS (COLLAB_ID, EMAIL, PASSWORD, NAME, FILE_IMAGE) VALUES (101, 'organization.sample1@gmail.com', 'sample0001', 'Jira', 'jira.jpg');
INSERT INTO COLLABORATORS (COLLAB_ID, EMAIL, PASSWORD, NAME, FILE_IMAGE) VALUES (102, 'organization.sample2@example.com', 'sample0002', 'BitBucker', 'bitbucker.png');
INSERT INTO COLLABORATORS (COLLAB_ID, EMAIL, PASSWORD, NAME, FILE_IMAGE) VALUES (103, 'organization.sample3@example.com', 'sample0003', 'Remind', 'remind.jpg');
INSERT INTO COLLABORATORS (COLLAB_ID, EMAIL, PASSWORD, NAME, FILE_IMAGE) VALUES (104, 'organization.sample4@example.com', 'sample0004', 'ResearchHub', 'researchhub.png');
INSERT INTO COLLABORATORS (COLLAB_ID, EMAIL, PASSWORD, NAME) VALUES (105, 'organization.sample5@example.com', 'sample0005', 'TeamPulse');

INSERT INTO SERVICES (SERVICE_ID, NAME, DESCRIPTION, CATEGORY, SERVICE_TYPE, COLLABORATOR_ID, MINIMUM_PAID, COST_SCOPE) VALUES (101, 'Jira Confluence', 'With 24/7 support, unlimited storage, 99.9% uptime SLA, and advanced features, Confluence Premium improves team productivity and scales as fast as your organization.', 'any', 'project', 101, 0, 170);
INSERT INTO SERVICES (SERVICE_ID, NAME, DESCRIPTION, CATEGORY, SERVICE_TYPE, COLLABORATOR_ID, MINIMUM_PAID, COST_SCOPE) VALUES (102, 'Bitbucket Projects', 'Bitbucket Projects seamlessly integrates version control and project management. Plan, track, and manage your software projects efficiently with Bitbucket.', 'software', 'project', 102, 0, 99);
INSERT INTO SERVICES (SERVICE_ID, NAME, DESCRIPTION, CATEGORY, SERVICE_TYPE, COLLABORATOR_ID, MINIMUM_PAID, COST_SCOPE) VALUES (103, 'Redmine Software Suite', 'Redmine Software Suite provides a comprehensive solution for project management, issue tracking, and collaboration. Enhance your software development process with Redmine.', 'software', 'project', 103, 0 ,100);
INSERT INTO SERVICES (SERVICE_ID, NAME, DESCRIPTION, CATEGORY, SERVICE_TYPE, COLLABORATOR_ID, MINIMUM_PAID, COST_SCOPE) VALUES (104, 'ResearchHub', 'ResearchHub provides advanced tools for managing and conducting research projects. Collaborate, analyze data, and streamline your research process with ResearchHub.', 'research', 'project', 104, 0, 389);