name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: true
        default: 'Manual trigger'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: mizpuno
          password: dckr_pat_ChJw8TImh9mnJx3L7U8j4lJWBLQ

      - name: Extract metadata (tags, labels) for Naming Server
        id: meta-naming-server
        uses: docker/metadata-action@v3
        with:
          images: mizpuno/backend-application-demo:naming-server-lastest
          
      - name: Build and push Naming Server image
        uses: docker/build-push-action@v2
        with:
          context: ./naming-server
          file: ./naming-server/Dockerfile
          push: true
          tags: ${{ steps.meta-naming-server.outputs.tags }}
          labels: ${{ steps.meta-naming-server.outputs.labels }}
     
      - name: Extract metadata (tags, labels) for Client Microservice
        id: meta-client-module
        uses: docker/metadata-action@v3
        with:
          images: mizpuno/backend-application-demo:client-microservice-lastest
            
      - name: Build and push Naming Server image
        uses: docker/build-push-action@v2
        with:
            context: ./client-microservice
            file: ./client-microservice/Dockerfile
            push: true
            tags: ${{ steps.meta-client-module.outputs.tags }}
            labels: ${{ steps.meta-client-module.outputs.labels }}
