name: Module Automatic Testing
on: [push]

jobs:
  build:
    name: Buinding a ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.11
      - name: Build and Test with Maven
        run: mvn verify --file pom.xml
